customer/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

urlpatterns = [
    path('upload/', views.upload_file, name='upload-file'),
    path('deletefile/', views.delete_file, name='delete-file'),
    path('supplier/', views.save_supplier, name='supplier-save'),
    path('supplier/delete/', views.delete_supplier, name='supplier-delete'),
    path('service_note/', views.save_service_note, name='service-note-save'),
    path('service_note/delete/', views.delete_service_note,
         name='service-note-delete'),
    path('app-data/', views.update_app_data, name='app-data'),
    path('requirement/', views.requirement, name='requirement'),
    path('deposit/', views.deposit_list, name='deposit-list'),
    path('deposit/search', views.deposit_search, name='deposit-search'),
    path('deposit/<int:pk>', views.deposit_view, name='deposit-view'),
    path('signed/',views.salesSigned_list,name='signed-list'),
    path('signed/search',views.salesSigned_search,name='signed-search'),
    path('signed/<int:pk>',views.salesSigned_view,name='signed-view'),
    path('on-file/', views.on_file_list, name='on-file-list'),
    path('on-file/search', views.on_file_search, name='on-file-search'),
    path('on-file/<int:pk>', views.on_file_view, name='on-file-view'),
    path('order/', views.order_list, name='order-list'),
    path('order/search', views.order_search, name='order-search'),
    path('order/<int:pk>', views.order_view, name='order-view'),
    path('installation/', views.installation_list, name='installation-list'),
    path('installation/search', views.installation_search, name='installation-search'),
    path('installation/<int:pk>', views.installation_view,
         name='installation-view'),
    path('account/', views.account_list, name='account-list'),
    path('download/', views.all_download, name='all-download'),
    path('reports/', views.all_download, name='all-download'),
    path('xls/', views.export_xls, name='export_xls'),
    path('account/search', views.account_search, name='account-search'),
    path('account/<int:pk>', views.account_view, name='account-view'),
    path('account/add_customer',views.add_customer_via_account,name='account-add-customer'),
    path('service/', views.service_list, name='service-list'),
    path('service/search', views.service_search, name='service-search'),
    path('service/<int:pk>', views.service_view, name='service-view'),
    path('finished/', views.finished_list, name='finished-list'),
    path('finished/search', views.finished_search, name='finished-search'),
    path('finished/<int:pk>', views.finished_view, name='finished-view'),
    path('global/search',views.global_search,name='global-search'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newLead/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('newLead/', views.newLead_list, name='newLead-list'),
    path('newLead/<int:pk>', views.newLead_view, name='newLead-view'),
    path('newLead/search', views.newLead_search, name='newLead-search'),

]

solarCRM/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('customer.urls')),
    path('', include('newLead.urls')),
    path('accounts/', include('allauth.urls')),
    path('mailserver/',include('mailserver.urls'))
]

customer/models.py
from django.contrib.auth import get_user_model
from django.core.validators import RegexValidator
from django.db import models

numeric = RegexValidator(r'^[0-9]*$', 'Only numeric characters are allowed.')


class Lead(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name if self.name else ''


USER_PROFILES = [
    ('user', 'User'),
    ('Installation', 'Installation'),
    ('installer', 'Installer'),
    ('salesman', 'Salesman'),
    ('account', 'Account'),
]


class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    title = models.CharField(
        max_length=20, choices=USER_PROFILES, default=USER_PROFILES[0][0])

    def __str__(self):
        return self.title if self.title else ''


class Payment(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name if self.name else ''


class Customer(models.Model):
    creator = models.ForeignKey(get_user_model(
    ), on_delete=models.CASCADE, null=True, blank=True, related_name='customer_creator')
    created_date = models.DateTimeField(auto_now_add=True)
    leads_from = models.ForeignKey(
        Lead, on_delete=models.CASCADE, null=True, blank=True)
    sales_person = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, null=True, blank=True, related_name='customer_salesman')
    agm = models.CharField(max_length=50, blank=True, null=True)  # optional
    date_signed = models.DateField(blank=True, null=True)  # optional
    customer_name = models.CharField(max_length=50)
    customer_address = models.CharField(
        max_length=200, blank=True, null=True)  # optional
    customer_email = models.EmailField(
        max_length=200, blank=True, null=True)  # optional
    phone_number = models.CharField(max_length=20, blank=True,
                                    null=True, validators=[numeric])  # optional
    follow_up = models.CharField(
        max_length=100, blank=True, null=True)  # optional
    customer_notes = models.CharField(
        max_length=500, blank=True, null=True)  # optional

    customer_check = models.BooleanField(default=False)
    
    created_from_account = models.BooleanField(default=False) # for adding customer via account
    

    def __str__(self):
        return self.customer_name if self.customer_name else ''

    class Meta:
        ordering = ['-created_date']
        permissions = [
            ("customer_list", "Can view New Customer List page"),
            ("customer_view", "Can view New Customer details"),
            ("deposit_list", "Can view Deposit List page"),
            ("deposit_view", "Can view Deposit details"),
            ("on_file_list", "Can view On File List page"),
            ("on_file_view", "Can view On File details"),
            ("order_list", "Can view Order List page"),
            ("order_view", "Can view Order details"),
            ("installation_list", "Can view Installation List page"),
            ("installation_view", "Can view Installation details"),
            ("account_list", "Can view Account List page"),
            ("account_view", "Can view Account details"),
            ("service_list", "Can view Service List page"),
            ("service_view", "Can view Service details"),
            ("finished_list", "Can view Finished List page"),
            ("finished_view", "Can view Finished details"),
            ("customer_view_others", "Can view Customers of other users"),
            ("delete_customer_data", "Can delete Customer data"),
            ("add_new_customer_via_account","Add new customer via account"),
            ("sales_signed","See already signed customer"),
            ("view_reports", "Can view reports")
        ]


class Service(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    agm = models.IntegerField()
    customer_name = models.CharField(max_length=50)
    customer_address = models.CharField(max_length=200)
    customer_email = models.EmailField(max_length=200)
    customer_phone = models.CharField(max_length=20, validators=[numeric])
    installation_date = models.DateField()
    installer = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    notes = models.CharField(max_length=500)

    def __str__(self):
        return self.customer_name if self.customer_name else ''

# Models for new requirements


class RoofType(models.Model):
    # Model added for future customization
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name if self.name else ''


class Storey(models.Model):
    # Model added for future customization
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name if self.name else ''


class ElectricPower(models.Model):
    # Model added for future customization
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name if self.name else ''


class Requirement(models.Model):
    """
    Users create a customer and the information is stored in a database.
    """
    created_date = models.DateTimeField(auto_now_add=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    kw = models.CharField(max_length=50, null=True, blank=True)
    panel = models.CharField(max_length=50, null=True, blank=True)
    panel_pcs = models.IntegerField(null=True, blank=True)
    inverter = models.CharField(max_length=50, null=True, blank=True)
    inverter_pcs = models.IntegerField(null=True, blank=True)
    # linked as a foreign key for flexibility
    roof_type = models.ForeignKey(
        RoofType, on_delete=models.CASCADE, null=True, blank=True)
    # linked as a foreign key for flexibility
    storey = models.ForeignKey(
        Storey, on_delete=models.CASCADE, null=True, blank=True)
    # linked as a foreign key for flexibility
    electric_power = models.ForeignKey(
        ElectricPower, on_delete=models.CASCADE, null=True, blank=True)
    installation_notes = models.CharField(
        max_length=500, null=True, blank=True)

    finance = models.CharField(max_length=50,default='No',null=True, blank=True) # changed from Boolean to Charfield


    system_price = models.FloatField(null=True, blank=True,default=0.00)
    extra_amount = models.FloatField(null=True, blank=True,default=0.00)
    total_price = models.FloatField(null=True, blank=True,default=0.00)
    deposit_amount = models.FloatField(null=True, blank=True,default=0.00)
    last_amount = models.FloatField(null=True, blank=True,default=0.00)
    status = models.CharField(max_length=50, default='CREATED')

    deposit_date_paid = models.DateField(null=True, blank=True)
    deposit_payment = models.ForeignKey(
        Payment, on_delete=models.CASCADE, related_name='requirement_deposit_payment', null=True, blank=True)

    #this is the installation data
    installation_date = models.DateField(null=True, blank=True)
    installer = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, null=True, blank=True)
    installer_amount = models.FloatField(null=True, blank=True,default=0.00)
    installer_date_paid = models.DateField(null=True, blank=True)
    Installer_notes = models.CharField(max_length=500, null=True, blank=True,default="")

    order_paid = models.BooleanField(default=False)

    # This is the stc fields
    unit =  models.IntegerField(null=True, blank=True)
    unit_price = models.FloatField(null=True, blank=True,default=0.00)
    stc_application = models.BooleanField(default=False)
    balance_due =  models.DateField(null=True, blank=True)
    stc_amount_payment = models.FloatField(null=True, blank=True,default=0.00)
    stc_notes = models.CharField(max_length=500, null=True, blank=True)
    STC_PAYMENT = models.FloatField(null=True, blank=True,default=0.00)
    stc_amount = models.FloatField(null=True, blank=True,default=0.00)
    stc_date_paid = models.DateField(null=True, blank=True)

    pcs = models.IntegerField(null=True, blank=True)

    # This is the last amount fields
    last_amount_paid_date = models.DateField(null=True, blank=True)
    last_amount_payment = models.FloatField(null=True, blank=True,default=0.00)
    last_amount_payment_method = models.ForeignKey(
        Payment, on_delete=models.CASCADE, related_name='requirement_last_amount_payment', null=True, blank=True)
    last_amount_balance_due =  models.FloatField(null=True, blank=True,default=0.00)
    last_amount_notes = models.CharField(max_length=500, null=True, blank=True)

    power_connection = models.CharField(max_length=50, null=True, blank=True)
    meter_connection = models.CharField(max_length=50, null=True, blank=True)
    MNI = models.CharField(max_length=50, null=True, blank=True)
    application =  models.BooleanField(default=False)

    def __str__(self):
        return self.customer.customer_name if self.customer.customer_name else ''

    @property
    def supplier_status(self):
        """Summarizes suppliers information to display in account list view"""
        supplier_data = []
        for supplier in self.supplier_set.all():
            supplier_data.append('{}: {}'.format(supplier.supplier_name, 'Paid' if supplier.supplier_date_paid else '$ {}'.format(
                supplier.supplier_amount) if supplier.supplier_amount else '-'))
        return '\n'.join(supplier_data)

    @property
    def suppliers_paid(self):
        return all([True if supplier.supplier_date_paid else False for supplier in self.supplier_set.all()])

    @property
    def installation_paid(self):
        """Returns whether the installation has a pay date or not"""
        return 'Paid' if self.installer_date_paid else '$ {}'.format(self.installer_amount) if self.installer_amount else None

    @property
    def deposit_paid(self):
        return 'Paid' if self.deposit_date_paid else '$ {}'.format(self.deposit_amount) if self.deposit_amount else None

    @property

customer/templates/customer/fields/account_search-fields.html
<div id="search-form" class="pb-3">
    
    <div class="form-row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <form id="search_form" method="post" action="{% url 'global-search' %}">
                {% csrf_token %}
                <div class="form-group col-md-10" id="searchFormGroup">
                    {% if search_value %}
						<input type="text" class="form-control" id="current_tab" name="current_tab" value="{{ current_tab }}" hidden>
                        <input type="text" class="form-control" id="search_value" name="search_value" value="{{search_value}}" placeholder="Enter...">
						
                    {% else %}
						<input type="text" class="form-control" id="current_tab" name="current_tab" value="{{ current_tab }}" hidden>
                        <input type="text" class="form-control" id="search_value" name="search_value" placeholder="Enter...">						
                    {% endif %}
    
                </div>
                    <button type="submit" id="btn-search" class="btn btn-primary">Search</button>				
				</form>
				
				
			</div>
			<div class="col-md-2">
			<form id="search_form" method="get" action="{% url 'account-add-customer' %}">
					{% if not search_value and perms.customer.add_new_customer_via_account %}					
					<button type="submit" id="add_customer" class="btn btn-primary">Add Customer</button>
					{% endif %}
			</form>
			</div>
                
            
        </div>

        <div class="col-md-2">
            <form id="search_clear_form" method="get" action="{% url 'account-list' %}">
                {% csrf_token %}
                {% if search_value %}
                    <button type="submit" id="btn-search" class="btn btn-danger">Clear</button>
                {% endif %}
            </form>
        </div>
    </div>
</div>

customer/templates/customer/fields/connection_field.html
{% if power_meter_connection_disable %}
    <div></div>
{% else %}
    <h2 class="py-3">Connection</h2>

    <div class="row">
        <div class="form-group col-6">
            <label for="power-connection" class="col-sm-12 col-form-label">Power connection</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="power-connection" name="power_connection"
                       value="{{ requirement.power_connection|default:'' }}" placeholder="Enter power connection"
                       {% if required_fields.system_fields.power_connection %}required="required"{% endif %}>
            </div>
        </div>

        <div class="form-group col-6">
            <label for="meter-connection" class="col-sm-12 col-form-label">Meter connection</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="meter-connection" name="meter_connection"
                       value="{{ requirement.meter_connection|default:'' }}" placeholder="Enter meter connection"
                       {% if required_fields.system_fields.meter_connection %}required="required"{% endif %}>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="form-group col-6">
            <label for="power-connection" class="col-sm-12 col-form-label">MNI</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="MNI" name="MNI"
                       value="{{ requirement.MNI|default:'' }}" placeholder="MNI"
                       {% if required_fields.system_fields.power_connection %}required="required"{% endif %}>
            </div>
        </div>


        <div class="form-group col-6">
            <label for="customer-check" class="col-sm-2 col-form-label">Application</label>
            <div class="col-sm-10 pl-5">
                <input class="form-check-input" type="checkbox" id="Application" name="Application"
                        {% if requirement.application %}
                       checked {% endif %}>
            </div>
        </div>

    </div>




{% endif %}

customer/templates/customer/fields/credit-card-fields.html
<div class="form-row">
    <div class="form-group col-md-6">
        <label for="credit-card">Credit card</label>
        <input type="text" class="form-control" pattern="^[0-9]*$" id="credit-card" name="credit_card" placeholder="Enter credit card" value="{{credit_card.credit_card|default:''}}">
    </div>
    <div class="form-group col-md-6">
        <label for="expires">Expires</label>
        <input type="text" class="form-control" id="expires" name="expires" value="{{credit_card.expires|date:'m/Y'}}" placeholder="mm/yyyy" data-provide="datepicker" data-date-format="mm/yyyy" data-date-autoclose="true" data-date-view-mode="months" data-date-min-view-mode="months">
    </div>
</div>

customer/templates/customer/fields/customer-check-fields.html
<div class="form-group col-6">
    <h2 class="py-3">Customer check</h2>
<br>
    <div class="row">
        <label for="customer-check" class="col-sm-2 col-form-label">Checked</label>
        <div class="col-sm-10 pl-5">
            <input class="form-check-input" type="checkbox" id="customer-check" name="customer_check"
                    {% if customer.customer_check %} checked {% endif %}>
        </div>
    </div>
</div>

customer/templates/customer/fields/deposit-fields.html
<div class="form-row">
    <div class="form-group col-md-4">
        <label for="deposit-mirror">Deposit</label>
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text amount-field">$</span>
            </div>
            <input type="number" class="form-control" id="deposit-mirror" disabled value="{{requirement.deposit_amount}}" placeholder="0.00" step="0.01"   >
        </div>
    </div>
    <div class="form-group col-md-4">
        <label for="deposit-date-paid">Date paid</label>
        <input type="text" class="form-control" id="deposit-date-paid" name="deposit_date_paid" value="{{requirement.deposit_date_paid|date:'d/m/Y'}}" placeholder="dd/mm/yyyy" data-provide="datepicker" data-date-format="dd/mm/yyyy" data-date-autoclose="true"
            data-date-today-btn="linked" data-date-clear-btn="true" {% if required_fields.deposit_fields.deposit_date_paid %}required="required"{% endif %}>
    </div>
    <div class="form-group col-md-4">
        <label for="deposit-payment">Payment</label>
        <select id="deposit-payment" name="deposit_payment" class="form-control" {% if required_fields.deposit_fields.deposit_payment %}required="required"{% endif %}>
            <option value="">Select...</option>
            {% for payment in payments %}
            <option value="{{payment.id}}" {% if payment.id == requirement.deposit_payment_id %}selected="selected"{% endif %}>{{payment.name}}</option>
            {% endfor %}
        </select>
    </div>

</div>

customer/templates/customer/fields/installation-fields.html
<div class="form-row">
    <div class="form-group col-md-3">
        <label for="installation-date">Installation Date</label>
        <input type="text" class="form-control" id="installation-date" name="installation_date" value="{{requirement.installation_date|date:'d/m/Y'}}" placeholder="dd/mm/yyyy" data-provide="datepicker" data-date-format="dd/mm/yyyy" data-date-autoclose="true"
            data-date-today-btn="linked" data-date-clear-btn="true" {% if required_fields.installation_fields.installation_date %}required="required"{% endif %}>
    </div>
    <div class="form-group col-md-3">
        <label for="installer">Installer</label>
        <select id="installer" name="installer" class="form-control" {% if required_fields.installation_fields.installer %}required="required"{% endif %}>
            <option value="">Select...</option>
            {% for installer in installers %}
            <option value="{{installer.id}}" {% if installer.id == requirement.installer_id %}selected="selected"{% endif %}>{{installer.username}}</option>
            {% endfor %}
        </select>
    </div>
{% if options.installer_payment_data_enabled %}
{% if perms.customer.change_payment %}
    <div class="form-group col-md-3">
        <label for="installer-amount">Installer Amount</label>
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text amount-field">$</span>
            </div>
            <input type="number" class="form-control" id="installer-amount" name="installer_amount" value="{{requirement.installer_amount|floatformat:2}}" placeholder="0.00" step="0.01" {% if required_fields.installation_fields.installer_amount %}required="required"{% endif %}>
        </div>
    </div>
    <div class="form-group col-md-3">
        <label for="installer-date-paid">Installer Date Paid</label>
        <input type="text" class="form-control" id="installer-date-paid" name="installer_date_paid" value="{{requirement.installer_date_paid|date:'d/m/Y'}}" placeholder="dd/mm/yyyy" data-provide="datepicker" data-date-format="dd/mm/yyyy" data-date-autoclose="true"
            data-date-today-btn="linked" data-date-clear-btn="true" {% if required_fields.installation_fields.installer_date_paid %}required="required"{% endif %}>
    </div>
    {% endif %}
</div>


<div class="form-group row">
    <label for="installation-notes" class="col-sm-2 col-form-label">Installer Notes</label>
    <div class="col-sm-10">
        <textarea class="form-control" id="installer-notes" name="installer_notes" placeholder="Enter installation notes" rows="3" {% if required_fields.installation_fields.installer_notes %}required="required"{% endif %}>{{requirement.Installer_notes|default:""}}</textarea>
    </div>
</div>

    {% else %}
    </div>
{% endif %}

customer/templates/customer/fields/requirement-fields.html
<div class="d-none">
    <input type="number" name="requirement_pk" value="{{ requirement.pk }}">
</div>


<div class="form-row">

    <div class="form-group col-md-4">
        <label for="kw">KW</label>
        <input type="text" class="form-control" id="kw" name="kw" value="{{ requirement.kw|default:'' }}"
               placeholder="Enter KW" {% if required_fields.system_fields.kw %}required="required"{% endif %}>
    </div>


    <div class="form-group col-md-2">
        <label for="panel">Panel</label>
        <input type="text" class="form-control" id="panel" name="panel" value="{{ requirement.panel|default:'' }}"
               placeholder="Enter panel" {% if required_fields.system_fields.panel %}required="required"{% endif %}>
    </div>
    <div class="form-group col-md-2">
        <label for="panel-pcs">pcs</label>
        <input type="number" class="form-control form-control-sm" id="panel-pcs" name="panel_pcs"
               value="{{ requirement.panel_pcs }}"
               placeholder="Enter pcs"
               {% if required_fields.system_fields.panel_pcs %}required="required"{% endif %}>
    </div>

    <div class="form-group col-md-2">
        <label for="inverter">Inverter</label>
        <input type="text" class="form-control" id="inverter" name="inverter"
               value="{{ requirement.inverter|default:'' }}" placeholder="Enter inverter"
               {% if required_fields.system_fields.inverter %}required="required"{% endif %}>
    </div>
    <div class="form-group col-md-2">
        <label for="inverter-pcs">Inverter pcs</label>
        <input type="number" class="form-control form-control-sm" id="inverter-pcs" name="inverter_pcs"
               value="{{ requirement.inverter_pcs }}" placeholder="Enter panel pcs"
               {% if required_fields.system_fields.inverter_pcs %}required="required"{% endif %}>
    </div>
</div>

<div class="row">

    <div class="form-group col-md-4">
        <label for="roof-type">Roof Type</label>
        <div>
            <select name="roof_type" id="roof-type" class="form-control"
                    {% if required_fields.system_fields.roof_type %}required="required"{% endif %}>
                <option value="">Select...</option>
                {% for roof_type in roof_types %}
                    <option value="{{ roof_type.id }}"
                            {% if roof_type.id == requirement.roof_type_id %}selected="selected"{% endif %}>{{ roof_type.name }}</option>
                {% endfor %}
            </select>
        </div>
    </div>

    <div class="form-group col-md-4">

        <label for="storey">Storey</label>
        <div>
            <select name="storey" id="storey" class="form-control"
                    {% if required_fields.system_fields.storey %}required="required"{% endif %}>
                <option value="">Select...</option>
                {% for storey in storeys %}
                    <option value="{{ storey.id }}"
                            {% if storey.id == requirement.storey_id %}selected="selected"{% endif %}>{{ storey.name }}</option>
                {% endfor %}
            </select>
        </div>
    </div>

    <div class="form-group col-md-4">
        <label for="electric-power">Electric Power</label>
        <div>
            <select name="electric_power" id="electric-power" class="form-control"
                    {% if required_fields.system_fields.electric_power %}required="required"{% endif %}>
                <option value="">Select...</option>
                {% for electric_power in electric_powers %}
                    <option value="{{ electric_power.id }}"
                            {% if electric_power.id == requirement.electric_power_id %}selected="selected"{% endif %}>{{ electric_power.name }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
</div>

<div class="form-group row">
    <div class="form-group col-md-12">
        <label for="installation-notes">Installation Notes</label>
        <div>
        <textarea class="form-control" id="installation-notes" name="installation_notes"
                  placeholder="Enter installation notes" rows="3"
                  {% if required_fields.system_fields.installation_notes %}required="required"{% endif %}>{{ requirement.installation_notes|default:"" }}</textarea>
        </div>
    </div>
</div>
{% if perms.customer.change_payment %}
<div class="form-group row">`
    <div class="form-group ">
        <label for="extra-amount" class="col-sm-12 col-form-label">Extra amount</label>
        <div class="col-sm-10">
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text amount-field">$</span>
                </div>
                <input type="number" class="form-control" id="extra-amount" name="extra_amount"
                       value="{% if requirement.extra_amount is not none %}{{ requirement.extra_amount|floatformat:2 }}{% else %}0{% endif %}"   placeholder="0.00" step="0.01"
                >
            </div>
        </div>
    </div>


    <div class="form-group ">
        <label for="extra-amount" class="col-sm-12 col-form-label">System Price</label>
        <div class="col-sm-10">
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text amount-field">$</span>
                </div>
                <input type="number" class="form-control" id="system-price" name="system_price"
                       value="{{ requirement.system_price|floatformat:2 }}" required="required"   placeholder="0.00" step="0.01"
                >
            </div>
        </div>
    </div>


</div>


<div class="form-group row">

    <div class="form-group ">
        <label for="total-amount" class="col-sm-12 col-form-label">Total amount</label>
        <div class="col-sm-10">
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text amount-field">$</span>
                </div>
                <input type="number" class="form-control" id="total-price" name="total_price"
                       value="{{ requirement.total_price|floatformat:2 }}" placeholder=0
                       {% if required_fields.system_fields.total_price %}required="required"
                       readonly="readonly"{% endif %}   placeholder="0.00" step="0.01"   >
            </div>
        </div>
    </div>
    <div class="form-group ">
        <label for="deposit-amount" class="col-sm-12 col-form-label">Deposit</label>
        <div class="col-sm-10">
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text amount-field">$</span>
                </div>
                <input type="number" class="form-control" id="deposit-amount" name="deposit_amount"
                       value="{{ requirement.deposit_amount|floatformat:2 }}" placeholder="0"
                       {% if required_fields.system_fields.deposit_amount %}required="required"{% endif %}   placeholder="0.00" step="0.01"   >
            </div>
        </div>
    </div>

    <div class="form-group ">
        <label for="last-amount" class="col-sm-12 col-form-label">Last amount</label>
        <div class="col-sm-10">
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text amount-field">$</span>
                </div>
                <input type="number" class="form-control" id="last-amount" name="last_amount"
                       value="{{ requirement.last_amount|floatformat:2 }}" placeholder="0" readonly="readonly"
                       {% if required_fields.system_fields.last_amount %}required="required"{% endif %}   placeholder="0.00" step="0.01"   >
            </div>
        </div>
    </div>
</div>
{% include 'customer/fields/credit-card-fields.html' %}

{% endif %}